#!/bin/bash

[[ -z "${GPT4_CLI_PATH_PREFIX}" ]] && echo "Please set GPT4_CLI_PATH_PREFIX environment variable" && exit 1;

source $GPT4_CLI_PATH_PREFIX/bin/activate
python3 $GPT4_CLI_PATH_PREFIX/dalle.py $@